# -*- coding: utf-8 -*-
"""Movie-recommendation-system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YuLCg9jdRtcITfkOdI8OX4UNVtwTIHcp
"""

# ==============================
# 1. Import Libraries
# ==============================

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity


# ==============================
# 2. Load Dataset
# ==============================

# Load movie dataset
data = pd.read_csv("../data/movies.csv")

print("First 5 rows of dataset:")
print(data.head())


# ==============================
# 3. Select Important Features
# ==============================

# We will combine important columns
features = ["genres", "keywords", "tagline", "cast", "director"]


# Replace missing values with empty string
for feature in features:
    data[feature] = data[feature].fillna("")


# ==============================
# 4. Combine Features
# ==============================

combined_features = (
    data["genres"] + " " +
    data["keywords"] + " " +
    data["tagline"] + " " +
    data["cast"] + " " +
    data["director"]
)


# ==============================
# 5. Convert Text to Vectors
# ==============================

vectorizer = CountVectorizer()
feature_vectors = vectorizer.fit_transform(combined_features)


# ==============================
# 6. Calculate Similarity
# ==============================

similarity = cosine_similarity(feature_vectors)


# ==============================
# 7. Recommendation Function
# ==============================

def recommend_movie(movie_name):

    movie_list = data["title"].tolist()

    if movie_name not in movie_list:
        print("Movie not found in dataset")
        return

    movie_index = data[data.title == movie_name].index[0]

    similarity_scores = list(enumerate(similarity[movie_index]))

    sorted_movies = sorted(similarity_scores, key=lambda x: x[1], reverse=True)

    print("\nMovies recommended for", movie_name, ":\n")

    i = 1
    for movie in sorted_movies[1:6]:
        index = movie[0]
        title = data.iloc[index]["title"]
        print(i, ".", title)
        i += 1


# ==============================
# 8. Test Recommendation
# ==============================

recommend_movie("Avatar")

