# -*- coding: utf-8 -*-
"""fake-news-detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YuLCg9jdRtcITfkOdI8OX4UNVtwTIHcp
"""

# ======================================
# Fake News Detection using Logistic Regression
# ======================================

# 1️⃣ Import Libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 2️⃣ Load Dataset
# Make sure your CSV has at least 'text' and 'label' columns
data = pd.read_csv("../data/news.csv")
print("Dataset loaded successfully!")
print("Columns:", data.columns.tolist())
print("Number of samples:", len(data))

# 3️⃣ Data Preprocessing
# Fill missing text with empty strings
data['text'] = data['text'].fillna('')

# Optional: You can lowercase text, remove punctuation, etc. for better results
# data['text'] = data['text'].str.lower()

# 4️⃣ Split Dataset into Training and Testing
X = data['text']
y = data['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
print(f"Training samples: {len(X_train)}, Testing samples: {len(X_test)}")

# 5️⃣ Convert Text to Features using TF-IDF
tfidf = TfidfVectorizer(stop_words='english', max_df=0.7)
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)
print("Text vectorization completed!")

# 6️⃣ Train Logistic Regression Model
model = LogisticRegression()
model.fit(X_train_tfidf, y_train)
print("Model training completed!")

# 7️⃣ Make Predictions on Test Set
y_pred = model.predict(X_test_tfidf)

# 8️⃣ Evaluate Model Performance
print("\nModel Evaluation:")
print("-----------------")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

# 9️⃣ Predict a Custom News Article
def predict_news(text):
    """
    Predicts whether a news article is FAKE or REAL.
    Input: text (string)
    Output: prediction (FAKE/REAL)
    """
    vectorized_text = tfidf.transform([text])
    prediction = model.predict(vectorized_text)[0]
    print(f"\nNews: {text}\nPrediction: {prediction}")

# Example usage
sample_news = "Breaking news: Scientists discovered a new planet!"
predict_news(sample_news)